### ISSUE TITLE
AMing.SettingsExtensions与索敌插件冲突 导致不能使用

### ISSUE THREAD

**Issue by wyjtm** [AMMing/KcvPlugins#1]
AMing.SettingsExtensions与索敌插件冲突（https://github.com/Gizeta/KCV.ViewRangeCalc） 导致kcv不能使用

两个插件一起使用就会出现kcv已停止工作  求解决

**Comment by wyjtm** [comment]
已经联系到了索敌插件的作者.....是那个插件的问题......

**Comment by AMMing** [comment]
之前afk了半年多 都不知道索敌公式变了，等手头上的东西做完就去加下这个功能

**Comment by wyjtm** [comment]
e.........嗯 谢谢你 那个索敌插件的作者说他知道和其他插件的冲突问题  可他自己暂时没办法解决这个冲突的问题............................

劳烦你重新写个吧 也弄成独立插件吧 再次谢谢了.....

**Comment by AMMing** [comment]
不用客气，你们的支持是我最大的动力(σﾟ∀ﾟ)σ，现在在写一个大破警告的插件，这个做完估计就会去做索敌的插件了

**Comment by wyjtm** [comment]
伸手党为付出者说声谢谢是应该的  不用谦虚

大破警告赞一个  最好也带个弹窗提示

我把这三个插件分享给几个群里  他们都很喜欢这种单一功能的插件   每个人按不同喜好添加自己喜欢的插件很赞  那个功能插件和声音通知插件最受欢迎 比起kcv自带的好太多了 而且还能自定义声音  但是一弹出通知就冲突了....

接下来的活动 每个图的索敌公式的变更是必须的（普通图2-5和3-5都是用不同的索敌公式）   所以只好先用那个索敌插件了...

**Comment by AMMing** [comment]
我个人也喜欢根据自己喜欢组合插件，所以开发的时候尽量不同功能分成独立的一个插件，orz 其实SettingsExtensions 做得已经开始有点臃肿了，不过还好都是些小功能，索敌插件做完之后应该会做记录类型的插件吧
